// packages/react/src/button/Button.tsx
import { resolveButtonState, type ButtonSize, type ButtonVariant } from '@polyloom/core/button';
import { forwardRef, type ButtonHTMLAttributes } from 'react';

/** React Button 的公开属性。 */
export interface ButtonProps extends Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'disabled' | 'size'
> {
  disabled?: boolean;
  loading?: boolean;
  size?: ButtonSize;
  variant?: ButtonVariant;
}

/**
 * PolyLoom React 按钮。ref 与未知原生属性都会透传到实际 button 元素。
 */
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  {
    children,
    className,
    disabled = false,
    loading = false,
    size = 'md',
    type = 'button',
    variant = 'primary',
    ...nativeButtonProps
  },
  forwardedRef,
) {
  const buttonState = resolveButtonState({
    disabled,
    loading,
  });
  const classes = ['pl-button', `pl-button--${variant}`, `pl-button--${size}`, className]
    .filter(Boolean)
    .join(' ');

  return (
    <button
      {...nativeButtonProps}
      ref={forwardedRef}
      aria-busy={buttonState.ariaBusy}
      className={classes}
      disabled={buttonState.disabled}
      type={type}
    >
      {loading ? <span aria-hidden="true" className="pl-button__spinner" /> : null}
      <span className="pl-button__label">{children}</span>
    </button>
  );
});

// packages/vue/src/button/Button.vue
<script setup lang="ts">
import { resolveButtonState } from '@polyloom/core/button';
import { computed } from 'vue';
import type { ButtonProps } from './types.js';

defineOptions({
  name: 'PlButton',
  inheritAttrs: false,
});

const props = withDefaults(defineProps<ButtonProps>(), {
  disabled: false,
  loading: false,
  size: 'md',
  type: 'button',
  variant: 'primary',
});

const emit = defineEmits<{
  click: [event: MouseEvent];
}>();

const buttonState = computed(() =>
  resolveButtonState({
    disabled: props.disabled,
    loading: props.loading,
  }),
);

function handleClick(event: MouseEvent) {
  // disabled 原生按钮不会触发 click；这里额外保护程序化触发与未来渲染适配。
  if (buttonState.value.disabled) {
    event.preventDefault();
    event.stopImmediatePropagation();
    return;
  }

  emit('click', event);
}
</script>

<template>
  <button
    v-bind="$attrs"
    :aria-busy="buttonState.ariaBusy"
    :class="['pl-button', `pl-button--${variant}`, `pl-button--${size}`]"
    :disabled="buttonState.disabled"
    :type="type"
    @click="handleClick"
  >
    <span v-if="loading" aria-hidden="true" class="pl-button__spinner" />
    <span class="pl-button__label">
      <slot />
    </span>
  </button>
</template>
